name: StaticTests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: chef/chefdk:3
    steps:
    - uses: actions/checkout@v1
    - name: lint
      uses: fastrobot/chef-cookbook-action@v0.3.0
      with:
        chef_actions_task: 'lint'
