name: StaticTests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: chef/chefdk:3

    steps:
    - uses: actions/checkout@v1
    - name: cookstyle
      run: chef exec cookstyle
    - name: foodcritic
      run: chef exec foodcritic .
    - name: rspec
      run: chef exec rspec
      
